backend/controllers/ActionController.php
<?php
/**
 * @link      https://gitlab.com/nx-2/front
 * @copyright Copyright © 2017, 2018, 2022 Dimeo Ltd. under the terms of the GNU GPL, Version 3.0 (https://www.dimeo.ru/)
 * @license   https://gitlab.com/nx-2/front/-/blob/master/LICENSE.md
 * @author    A. Shchepetov
 */
namespace backend\controllers;

use backend\models\ActionItems;
use backend\models\ActionSearch;
use backend\models\PromoCodesSearch;
use Yii;
use backend\models\Action;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use backend\controllers\SiteController;
use \common\models\Edition;

/**
 * ActionController implements the CRUD actions for Action model.
 */
class ActionController extends SiteController
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        $behaviors = [
            'access' => yii\helpers\ArrayHelper::merge(
                parent::behaviors()['access'],
                [
                    // 'class' => AccessControl::className(),
                    'rules' => [
                        //залогиненым издателям разрешить кое что только
                        [
                            'actions' => ['update','index','create','generated','createitems','delete','delete-items','months'],
                            'allow' => true,
//                            'roles' => ['@'],
                            'roles' => ['subscribe_manager'],
//                            'matchCallback' => function ($rule, $action) {
//                                $allowedRoles = ['publisher','subscribe_manager','admin'];
//                                $allowed = Yii::$app->user->identity->isRole($allowedRoles);
//
//                                $a = Yii::$app->getUser()->can('manageActions');
//
//                                return (boolean)$allowed;
//                            },
                        ],
                    ],
                ]
            ),
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
        return $behaviors;
    }


    public function actionMonths(){
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;

        $journal_id = Yii::$app->request->getQueryParam('journal_id', false);

        if (!$journal_id)
            return false;

        $journal_id = intval($journal_id);
        $edition = Edition::findOne(['Message_ID' => $journal_id]);

        return yii\helpers\ArrayHelper::map($edition->editionPeriods, 'period', 'period');

//        if(!$journal=\common\models\NxPrice::find()->where(['publisher_id'=> Yii::$app->user->identity->publisher_id])->one())
//            return false;
//
//        $journal->mag_id=$journal_id;
//
//        if(!isset($journal->nxPriceItemsOne->edition))
//            return false;
//
//        $journal=$journal->nxPriceItemsOne->edition;
//
//        return  yii\helpers\ArrayHelper::map($journal->editionPeriods, 'period', 'period');
    }
    /**
     * Lists all Action models.
     * @return mixed
     */
    public function actionIndex()
    {

        $searchModel = new \backend\models\ActionSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'searchModel' => $searchModel,
        ]);
    }

    /**
     * Displays a single Action model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Action model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new \common\models\Action();
        $model->scenario = 'create';

        $modelItems=new \common\models\ActionItems();

        $model->action_code = $model->generateRandomString();
        $model->date_start=date('d-m-Y');
        $model->date_end=date('d-m-Y');
        $model->publisher_id=Yii::$app->user->identity->publisher_id;

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['update', 'id' => $model->id]);
        } else {
             return $this->render('create', [
                'model' => $model,
                'modelItems' => $modelItems,
            ]);
        }
    }

    /**
     * Updates an existing Action model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $searchModel = new \backend\models\PromoCodesSearch();
        $dataProviderPromoCodes = $searchModel->search(Yii::$app->request->queryParams,$id);

        $model = $this->findModel($id);
        $modelItems=new \common\models\ActionItems();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['update', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
                'modelItems' => $modelItems,
                'searchModel' => $searchModel,
                'dataProviderPromoCodes'=>$dataProviderPromoCodes
            ]);
        }
    }


    /**
     * Deletes an existing Action model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Delete items action
     * @param $id
     * @return \yii\web\Response
     */
    public function actionDeleteItems($id)
    {
//        $this->findModel($id, '\common\models\ActionItems')->delete();
        \common\models\ActionItems::findOne([ 'id' => $id])->delete();

        return $this->redirect(Yii::$app->request->referrer);
    }


    /**
     * save items action
     * @return \yii\web\Response
     */
    public function actionCreateitems()
    {

        $model = new \common\models\ActionItems();
        if ($model->load(Yii::$app->request->post())) {
            if (is_array($model->type)) {
               $model->setItems($model);
            }else{
                $model->save();
            }

        }

        return $this->redirect(['update', 'id' => $model->action_id]);


    }

    /**
     * @return string
     */
    public function actionGenerated()
    {

        Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;

        $actionId = Yii::$app->request->getQueryParam('id', false);
        $count = Yii::$app->request->getQueryParam('count', 0);


        if (empty($actionId))
            return false;

        $model = new \common\models\Action();
        $string = $model->generateRandomString(6, intval($count), $actionId);
        if (is_array($string))
            $string = implode(' '.PHP_EOL, $string);

        return ['string' => $string];


    }

    /**
     * Finds the Action model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Action the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {

        $searchModel = new ActionSearch();
        $dataProvider = $searchModel->search(['ActionSearch'=>['id'=>$id]]);

        if (!Yii::$app->user->identity->isRole(\common\models\User::ADMIN_ROLE) && ($dataProvider->getCount() == 0))
            throw new NotFoundHttpException('Извините, но вам сюда нельзя! Недостаточно прав.');

        if (($model = \common\models\Action::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }



}

backend/views/action/_form.php
<?php
/**
 * @link      https://gitlab.com/nx-2/admin
 * @copyright Copyright © 2017, 2018, 2022 Dimeo Ltd. under the terms of the GNU GPL, Version 3.0 (https://www.dimeo.ru/)
 * @license   https://gitlab.com/nx-2/admin/-/blob/master/LICENSE.md
 * @author    A. Shchepetov
 */


use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\date\DatePicker;

/* @var $this yii\web\View */
/* @var $model common\models\Action */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="action-form">

    <?php $form = ActiveForm::begin(); ?>
    <?= $form->errorSummary($model); ?>
    <label class="control-label" for="action-action_code">Код акции</label>
    <?=  DatePicker::widget([
         'name' => 'date_start',
        'type' => DatePicker::TYPE_INPUT,
         'value' => date('Y-m-d', strtotime($model->date_start)),
         'options' => ['placeholder' => 'Выберите дату'],
         'pluginOptions' => [
             'autoclose'=>true,
             'format' => 'yyyy-mm-dd',
         ]
     ]);?>

    <label class="control-label" for="action-action_code">Код акции</label>
    <?=  DatePicker::widget([
        'name' => 'date_end',
        'type' => DatePicker::TYPE_INPUT,
        'value' => date('Y-m-d', strtotime($model->date_end)),
        'options' => ['placeholder' => 'Выберите дату'],
        'pluginOptions' => [
            'autoclose'=>true,
            'format' => 'yyyy-mm-dd',
        ]
    ]);?>

    <?= $form->field($model, 'action_code')->textInput(['maxlength' => true,  'readonly'=>$model->isNewRecord ?  false : true]) ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true, 'enableAjaxValidation' => true]) ?>

    <?= $form->field($model, 'desc')->textarea(['rows' => 6]) ?>



    <div class="form-group">

        <?= $form->field($model, 'promocodes')->textarea(['rows' => 6, 'id' => 'promocodes']) ?>

    </div>

    <div class="input-group input-group-sm col-md-6">
        <input id="count" type="text" class="form-control" value="0">
        <span class="input-group-btn">
                      <button id="generated" type="button" class="btn btn-info btn-flat">Генерировать</button>
                    </span>
    </div>


    <div class="clearfix"></div>
<br>

    <div class="form-group">
        <?= Html::submitButton('Сохранить', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
        <?= Html::a(
        '<i class=\"fa fa-icon\"></i> Удалить акцию ' ,
        '/action/delete?id=' . $model->id,
        [
        'label' => 'Удалить',
        'aria-label' => 'Удалить',
        'data-confirm'=>'Вы уверены, что хотите удалить акцию?',
        'data-method'=> 'post',
        'data-pjax' => '1',
        'class' => 'btn btn-danger',
        ]);?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

<?php
use yii\helpers\Url;

$url = Url::toRoute(['generated', 'id' => $model->action_code]);
$script = <<< JS

$('#generated').click(function() {
var count= $('#count').val(); 
 $.ajax({
        dataType: 'json',
        type: "POST",
        url: "$url&count="+count,
        success: function(jsondata){
            $('#promocodes').html(jsondata.string);
        },
        error: function(jsondata) {
                $('#promocodes').html('ошибка генерации');
         }
      });

})


JS;

$this->registerJs($script, yii\web\View::POS_END);
?>

backend/views/action/_form_mag.php
<?php
/**
 * @link      https://gitlab.com/nx-2/admin
 * @copyright Copyright © 2017, 2018, 2022 Dimeo Ltd. under the terms of the GNU GPL, Version 3.0 (https://www.dimeo.ru/)
 * @license   https://gitlab.com/nx-2/admin/-/blob/master/LICENSE.md
 * @author    A. Shchepetov
 */


use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\grid\GridView;
use yii\data\ActiveDataProvider;
use kartik\select2\Select2;

/* @var $this yii\web\View */
/* @var $model common\models\Action */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="action-form">

    <fieldset <?= (!$model->id) ? "disabled" : "" ?>>
        <?php $form = ActiveForm::begin(['action' => ['createitems'], 'id' => 'forum_post', 'method' => 'post',]); ?>
        <?= $form->errorSummary($modelItems); ?>

        <?php
        echo $form->field($modelItems, 'mag_id')->dropDownList($modelItems::getAllJournals(), [
            'prompt' => Yii::t('app', 'Укажите журнал'),
            'data-trigger' => 'dep-drop',
            'data-target' => '#select-moths',
            'data-url' => \yii\helpers\Url::to(['/action/months']),
            'data-name' => 'journal_id',
            'id' => 'select-journal',
        ]   );
        ?>
        <?= $form->field($modelItems, 'months')->dropDownList([], [
            'prompt' => Yii::t('app', 'Укажите срок подписки'),
            'disabled' => true,
            'id' => 'select-moths',
        ]) ?>


        <?php

        echo $form->field($modelItems, 'type')->widget(Select2::classname(), [
            'data' =>['paper' => 'бумажная версия',
                'pdf' => 'PDF'],
            'language' => 'ru',
            'theme' => 'default', //'default classic bootstrap, krajee'
            'options' => ['placeholder' => 'Укажите тип'],
            'pluginOptions' => [
                'allowClear' => true,
                'multiple' => true,
            ],
        ]);
        ?>

        <?= $form->field($modelItems, 'discount')->textInput() ?>
        <?= $form->field($modelItems, 'action_id')->hiddenInput(['value' => $model->id])->label(false); ?>


        <div class="form-group">
            <?= Html::submitButton('Добавить', ['class' => 'btn btn-primary']) ?>
        </div>

        <?php ActiveForm::end(); ?>
    </fieldset>
</div>
<?php if (!$model->id): ?>
    <div class="alert alert-success alert-dismissible">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <h4><i class="icon fa fa-info"></i> Внимание!</h4>
        В начале необходимо сохранить акцию
    </div>
<?php endif; ?>



<?php
if (!empty($model->actionItems)) {

    $query = \common\models\ActionItems::find()->where(['=', 'action_id', $model->id]);
    $dataProvider = new ActiveDataProvider([
        'query' => $query,
    ]);


    echo GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            /*         [
                         'attribute' => 'action_id',
                         'value' => 'action.name'
                     ],*/
            ['attribute' => 'mag_id',
                'value' => function ($model, $key, $index) {
                    $name = \common\models\ActionItems::getOneJournals($model->mag_id);
                    return $name['full_name'];
                },
                'format' => 'raw'],

            'months',
            'type',
            'discount',

            ['class' => 'yii\grid\ActionColumn',
                'header' => 'Действие',
                'template' => '{delete}',
                'buttons' => [
                    'delete' => function ($url, $model) {
                        return Html::a('<span class="glyphicon glyphicon-trash"></span>', $url, [
                            'title' => Yii::t('app', 'lead-delete'),
                        ]);
                    }

                ],
                'urlCreator' => function ($action, $model, $key, $index) {
                    if ($action === 'delete') {
                        $url = 'delete-items/?id=' . $model->id;
                        return $url;
                    }

                }


            ],
        ],
    ]);
}
?>



    <?php
    $script = <<< JS
$("[data-trigger=dep-drop]").on("change", function() {
    // Собираем данные для отправки в действие контроллера
    var data = {};
    data[$(this).attr("data-name")] = $(this).val();
    // Контейнер для помещения ответа от сервера
    var target = $(this).attr("data-target");
    // Непосредственно отправка запроса на сервер
    $.getJSON(
        $(this).attr("data-url"), //URL
        data, // GET-параметры
        // Обработчик ответа сервера
        function(response, statusCode, xhr) {
            var slct = $(target); // jQuery-объект целевого тега
            slct.empty(); // Очищаем текущие <option>

            // Обходим каждый элемент массива из ответа сервера
            for (el in response) {
                // И добавляем его в конец <select>
                $("<option value=\"" + el + "\">" + response[el] + "</option>").appendTo(slct);
            }

            slct.removeAttr("disabled"); // Удаляем атрибут запрещающий изменение <select>
        }
    );
});
JS;
    $this->registerJs($script, yii\web\View::POS_END);
    ?>

backend/views/action/create.php
<?php
/**
 * @link      https://gitlab.com/nx-2/admin
 * @copyright Copyright © 2017, 2018, 2022 Dimeo Ltd. under the terms of the GNU GPL, Version 3.0 (https://www.dimeo.ru/)
 * @license   https://gitlab.com/nx-2/admin/-/blob/master/LICENSE.md
 * @author    A. Shchepetov
 */


use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model common\models\Action */

$this->title = 'Создать акцию';
$this->params['breadcrumbs'][] = ['label' => 'Акции', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>

<div class='col-md-5 col-sm-7 col-xs-12'>
    <div class='box box-primary'>
        <div class='box-header with-border'>
            <h3 class='box-title'>
                <?= Html::encode($this->title) ?>
            </h3>
        </div>
        <div style='padding: 20px;'>

            <?= $this->render('_form', [
                'model' => $model,
            ]) ?>        </div>
    </div>
</div>


<div class='col-md-5 col-sm-7 col-xs-12'>
    <div class='box box-primary'>
        <div class='box-header with-border'>
            <h3 class='box-title'>
                Издания участники
            </h3>
        </div>
        <div style='padding: 20px;'>

            <?= $this->render('_form_mag', [
                'model' => $model,
                'modelItems'=>$modelItems
            ]) ?>        </div>
    </div>
</div>





<div class="clearfix"></div>

backend/views/action/index.php
<?php
/**
 * @link      https://gitlab.com/nx-2/admin
 * @copyright Copyright © 2017, 2018, 2022 Dimeo Ltd. under the terms of the GNU GPL, Version 3.0 (https://www.dimeo.ru/)
 * @license   https://gitlab.com/nx-2/admin/-/blob/master/LICENSE.md
 * @author    A. Shchepetov
 */


use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
use kartik\date\DatePicker;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Акции';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="action-index">

    <h1><?= Html::encode($this->title); ?></h1>

    <p>
        <?= Html::a('Добавить акцию', ['create'], ['class' => 'btn btn-success']) ?>
    </p>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [

            [
                'attribute' => 'date_start',
                'value' => function($model,$key,$index,$column){
                    return date('Y-m-d',strtotime($model->date_start));
                },
                'filter' => DatePicker::widget([
                    'type' => DatePicker::TYPE_COMPONENT_PREPEND,
                    'layout' => '{input}{remove}',
                    'size' => 'xs',
//                    'convertFormat' => true,
                    'model' => $searchModel,
                    'attribute' => 'date_start',
                    'options' => [
                        'placeholder' => 'Укажите дату',
                        'value' => $searchModel->date_start,
                    ],
                    'pluginOptions' => [
                        'autoclose'=>true,
                        'format' => 'yyyy-mm-dd',
                    ]
                ]),
                'format' => 'html',
            ],
            [
                'attribute' => 'date_end',
                'value' => function($model,$key,$index,$column){
                    return date('Y-m-d',strtotime($model->date_end));
                },
                'filter' => DatePicker::widget([
                    'type' => DatePicker::TYPE_COMPONENT_PREPEND,
                    'layout' => '{input}{remove}',
                    'size' => 'xs',
//                    'convertFormat' => true,
                    'model' => $searchModel,
                    'attribute' => 'date_end',
                    'options' => [
                        'placeholder' => 'Укажите дату',
                        'value' => $searchModel->date_end,
                    ],
                    'pluginOptions' => [
                        'autoclose'=>true,
                        'format' => 'yyyy-mm-dd',
                    ]
                ]),
                'format' => 'html',
            ],

            'action_code',
            'name',
            // 'desc:ntext',

            ['class' => 'yii\grid\ActionColumn',
                'template' => '{update}',

            ],
        ],
    ]); ?>
</div>

backend/views/action/update.php
<?php
/**
 * @link      https://gitlab.com/nx-2/admin
 * @copyright Copyright © 2017, 2018, 2022 Dimeo Ltd. under the terms of the GNU GPL, Version 3.0 (https://www.dimeo.ru/)
 * @license   https://gitlab.com/nx-2/admin/-/blob/master/LICENSE.md
 * @author    A. Shchepetov
 */


use yii\helpers\Html;
use yii\grid\GridView;
use yii\data\ActiveDataProvider;

/* @var $this yii\web\View */
/* @var $model common\models\Action */

$this->title = 'Обновить акцию: ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Акции', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Обновить';
?>




<div class='col-md-5 col-sm-7 col-xs-12'>
    <div class='box box-primary'>
        <div class='box-header with-border'>
            <h3 class='box-title'>
                <?= Html::encode($this->title) ?>
            </h3>
        </div>
        <div style='padding: 20px;'>

            <?= $this->render('_form', [
                'model' => $model,
            ]) ?>        </div>
    </div>
</div>


<div class='col-md-5 col-sm-7 col-xs-12'>
    <div class='box box-primary'>
        <div class='box-header with-border'>
            <h3 class='box-title'>
                Издания участники
            </h3>
        </div>
        <div style='padding: 20px;'>

            <?= $this->render('_form_mag', [
                'model' => $model,
                'modelItems'=>$modelItems
            ]) ?>        </div>
    </div>
</div>



<div class='col-md-5 col-sm-7 col-xs-12'>
    <div class='box box-primary'>
        <div class='box-header with-border'>
            <h3 class='box-title'>
              Промокоды
            </h3>
        </div>
        <div style='padding: 20px;'>

    <?php
    if (!empty($model->promoCodes)) {

        $query = \common\models\PromoCodes::find()->where(['=', 'action_id', $model->id]);
        $dataProvider = new ActiveDataProvider([
            'query' => $query,
        ]);


        echo GridView::widget([
            'dataProvider' => $dataProviderPromoCodes,
            'filterModel' => $searchModel,
            'columns' => [
                'code',

            ],
        ]);
    }
    ?>




</div>
        </div>
    </div>

        <div class="clearfix"></div>

backend/views/action/view.php
<?php
/**
 * @link      https://gitlab.com/nx-2/admin
 * @copyright Copyright © 2017, 2018, 2022 Dimeo Ltd. under the terms of the GNU GPL, Version 3.0 (https://www.dimeo.ru/)
 * @license   https://gitlab.com/nx-2/admin/-/blob/master/LICENSE.md
 * @author    A. Shchepetov
 */


use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\Action */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Actions', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="action-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'date_start',
            'date_end',
            'action_code',
            'name',
            'desc:ntext',
        ],
    ]) ?>

</div>