backend/modules/admin/controllers/UserController.php
<?php
/**
 * @link      https://gitlab.com/nx-2/front
 * @copyright Copyright © 2017, 2018, 2022 Dimeo Ltd. under the terms of the GNU GPL, Version 3.0 (https://www.dimeo.ru/)
 * @license   https://gitlab.com/nx-2/front/-/blob/master/LICENSE.md
 * @author    A. Shchepetov
 */
namespace backend\modules\admin\controllers;

use Yii;
use common\models\User;
use backend\modules\admin\models\UserSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                // 'actions' => [
                //     'delete' => ['POST'],
                // ],
            ],
        ];
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single User model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new User();
        $model->setScenario('create');

        // $pr = Yii::$app->request->post('User', ['Password_repeat' => null])['Password_repeat'];
        // $model->Password_repeat = $pr;

        if ($model->load(Yii::$app->request->post()) && $model->uploadImage()) {

            if ($delCurrentImage = (Boolean) Yii::$app->request->post('delete-file', false) ) {
                $model->deleteOldImagesFiles();
                $model->avatar = null;
            }

            if ($model->save(false))
                Yii::$app->session->addFlash('success', 'Успешно создан новый пользователь.');
            else
                Yii::$app->session->addFlash('danger', 'Не сохранено!');

            return $this->redirect(['update', 'id' => $model->User_ID]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $model->setScenario('update');
        // $pr = Yii::$app->request->post('User')['Password_repeat'];
        // $model->Password_repeat = $pr;

        if ($model->load(Yii::$app->request->post()) && $model->uploadImage()) {

            if ($delCurrentImage = (Boolean) Yii::$app->request->post('delete-file', false) ) {
                $model->deleteOldImagesFiles();
                $model->avatar = null;
            }

            if ($model->save(false))
                Yii::$app->session->addFlash('success', 'Успешно сохранено.');
            else
                Yii::$app->session->addFlash('danger', 'Не сохранено!');
        }

        return $this->render('update', [
            'model' => $model,
        ]);

            // return $this->redirect(['view', 'id' => $model->User_ID]);
    }

    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {

        $model = $this->findModel($id);
        $login = $model->Login;
        if ($model  === null) {
            throw new NotFoundHttpException('The requested user does not exist.');
        }

        if( $model->delete() ) {
            Yii::$app->session->addFlash('success', 'Пользователь "' . $login . '" удален.');
            // return $this->redirect(['index']);
            return $this->actionIndex();
        } else {
            Yii::$app->session->addFlash('danger', 'Пользователь "' . $login . '" НЕ был удален.');
            return $this->redirect(['update', 'id' => $model->User_ID]);
        }
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            // $model->Password = '';
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/modules/admin/views/user/_search.php
<?php
/**
 * @link      https://gitlab.com/nx-2/admin
 * @copyright Copyright © 2017, 2018, 2022 Dimeo Ltd. under the terms of the GNU GPL, Version 3.0 (https://www.dimeo.ru/)
 * @license   https://gitlab.com/nx-2/admin/-/blob/master/LICENSE.md
 * @author    A. Shchepetov
 */


use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model backend\models\UserSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-search">

    <?php $form = ActiveForm::begin([
        'action' => ['user/index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'User_ID') ?>

    <?= $form->field($model, 'Password') ?>

    <?= $form->field($model, 'Checked') ?>

    <?= $form->field($model, 'Language') ?>

    <?= $form->field($model, 'Created') ?>

    <?php // echo $form->field($model, 'LastUpdated') ?>

    <?php // echo $form->field($model, 'Email') ?>

    <?php // echo $form->field($model, 'Login') ?>

    <?php // echo $form->field($model, 'FullName') ?>

    <?php // echo $form->field($model, 'LastName') ?>

    <?php // echo $form->field($model, 'FirstName') ?>

    <?php // echo $form->field($model, 'MidName') ?>

    <?php // echo $form->field($model, 'Confirmed') ?>

    <?php // echo $form->field($model, 'RegistrationCode') ?>

    <?php // echo $form->field($model, 'Auth_Hash') ?>

    <?php // echo $form->field($model, 'company') ?>

    <?php // echo $form->field($model, 'job') ?>

    <?php // echo $form->field($model, 'phone') ?>

    <?php // echo $form->field($model, 'country') ?>

    <?php // echo $form->field($model, 'city') ?>

    <?php // echo $form->field($model, 'address') ?>

    <?php // echo $form->field($model, 'street') ?>

    <?php // echo $form->field($model, 'house') ?>

    <?php // echo $form->field($model, 'building') ?>

    <?php // echo $form->field($model, 'flat') ?>

    <?php // echo $form->field($model, 'url') ?>

    <?php // echo $form->field($model, 'company_profile') ?>

    <?php // echo $form->field($model, 'sex') ?>

    <?php // echo $form->field($model, 'birthday') ?>

    <?php // echo $form->field($model, 'phone_prefix') ?>

    <?php // echo $form->field($model, 'fax_prefix') ?>

    <?php // echo $form->field($model, 'fax') ?>

    <?php // echo $form->field($model, 'region') ?>

    <?php // echo $form->field($model, 'district') ?>

    <?php // echo $form->field($model, 'index_num') ?>

    <?php // echo $form->field($model, 'open_email') ?>

    <?php // echo $form->field($model, 'avatar') ?>

    <?php // echo $form->field($model, 'UserType') ?>

    <?php // echo $form->field($model, 'Text') ?>

    <?php // echo $form->field($model, 'LastLoginDate') ?>

    <?php // echo $form->field($model, 'publisher_id') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/modules/admin/views/user/create.php
<?php
/**
 * @link      https://gitlab.com/nx-2/admin
 * @copyright Copyright © 2017, 2018, 2022 Dimeo Ltd. under the terms of the GNU GPL, Version 3.0 (https://www.dimeo.ru/)
 * @license   https://gitlab.com/nx-2/admin/-/blob/master/LICENSE.md
 * @author    A. Shchepetov
 */


use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model common\models\User */

$this->title = 'Создать пользователя';
$this->params['breadcrumbs'][] = ['label' => 'Пользователи(список)', 'url' => ['user/index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/modules/admin/views/user/index.php
<?php
/**
 * @link      https://gitlab.com/nx-2/admin
 * @copyright Copyright © 2017, 2018, 2022 Dimeo Ltd. under the terms of the GNU GPL, Version 3.0 (https://www.dimeo.ru/)
 * @license   https://gitlab.com/nx-2/admin/-/blob/master/LICENSE.md
 * @author    A. Shchepetov
 */


use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $searchModel backend\models\UserSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Пользователи';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Новый пользователь', ['user/create'], ['class' => 'btn btn-success']) ?>
    </p>
<?php Pjax::begin(); ?>    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            
            // ['class' => 'yii\grid\SerialColumn'],

            'User_ID',
            // 'Password',
            // 'Checked',

            [
                'class' => 'yii\grid\DataColumn',
                'attribute' => 'Checked',
                'content' => function ($model, $key, $index, $column) {
                    $checkbox = Html::checkbox('', (Boolean)$model->Checked, [
                        'id' => 'checked_' . $model->id,
                        'value' => $model->Checked,
                        // 'disabled' => true,
                        'onclick' => 'enabledClicked(event, "User","Checked")',
                    ]);
                    $label = Html::label('', 'checked_' . $model->id, ['class' => 'radio-check-label'], '');
                    $ajaxLoader = Html::tag('div', '', ['class' => 'ajax-load']);
                    $content = $ajaxLoader . $checkbox . $label;
                    $result = Html::tag('div', $content, ['class' => 'radio-check-wrap']);

                    return $result;
                },
                'contentOptions' => ['style' => 'vertical-align: middle;'],
                'filter' => ['1' => 'вкл', '0' => 'выкл'],
                'filterInputOptions' => ['style' => 'width:100%;height:100%', 'class' => 'form-control'],
            ],


            // 'Language',
            // 'Created',
            // 'LastUpdated',
            'Email:email',
            'Login',
            // 'FullName',
            'LastName',
            'FirstName',
            'MidName',
            // 'Confirmed',
            // 'RegistrationCode',
            // 'Auth_Hash:ntext',
            // 'company',
            // 'job',
            'phone',
            // 'country',
            // 'city',
            'address:ntext',
            // 'street',
            // 'house',
            // 'building',
            // 'flat',
            // 'url:url',
            // 'company_profile',
            // 'sex',
            // 'birthday',
            // 'phone_prefix',
            // 'fax_prefix',
            // 'fax',
            // 'region',
            // 'district',
            // 'index_num',
            // 'open_email:email',
            // 'avatar',

            [
                'attribute' => 'avatar',
                'content' => function ($model, $key, $index, $column) {
                    if (empty($model->avatar)) {
                        return Html::tag('span', '--', ['style' => 'text-align:center;display:inline-block;width:100%']);
                    } else {
                        $img = Html::img($model->avatar, ['width' => '70']);
                        return Html::tag('span', $img, ['style' => 'display: inline-block;width: 100%;text-align: center;']);
                    }
                },
                'filter' => false,
            ],

            // 'UserType',
            // 'Text:ntext',
            // 'LastLoginDate',
            [
                'attribute' => 'publisher',
                'value' => 'publisher.name',
            ],
            // 'rolesIds',
            [
                'attribute' => 'roles',
                'content' => function($model, $key, $index, $column){
                    $res = '';
                    foreach($model->roles as $r) {
                        $res .= '<small class="label pull-right bg-maroon" style="margin:0px 5px 5px 0px">' . $r['name'] . '</small>';
                    }
                    return ($res);
                },
                'filter' => false,
            ],
            [
                'class' => 'yii\grid\ActionColumn',
                'contentOptions' => ['style' => 'vertical-align: middle;'],
                // 'template' => '{update}',
                'template' => '{update}',
                // 'controller' => '',
                'buttons' => [
                    'update' => function ($url, $model, $key) {
                        $url = Url::to(['user/update', 'id' => $key]);
                        return Html::a(
                            '',
                            $url,
                            [
                                'title' => 'редактировать пользователя',
                                'aria-label' => 'редактировать',
                                'data-pjax' => 0,
                                'class' => 'fa fa-edit fa-font-18',
                            ]
                        );
                    },
                ],
            ],
            [
                'class' => 'yii\grid\ActionColumn',
                'contentOptions' => ['style' => 'vertical-align: middle;'],
                // 'template' => '{update}',
                'template' => '{delete}',
                // 'controller' => '',
                'buttons' => [
                    'delete' => function ($url, $model, $key) {
                        return Html::a(
                            '',
                            Url::to(['user/delete', 'id' => $key]),
                            [
                                'title' => 'Удалить пользователя',
                                'aria-label' => 'Удалить',
                                'data-confirm' => 'Вы уверены, что хотите удалить этого пользователя?',
                                'data-method' => 'post',
                                'data-pjax' => '#users-list',
                                'class' => 'fa fa-trash fa-font-18',
                            ]
                        );
                    },
                ],
            ],
        ],
    ]); ?>
<?php Pjax::end(); ?></div>

backend/modules/admin/views/user/update.php
<?php
/**
 * @link      https://gitlab.com/nx-2/admin
 * @copyright Copyright © 2017, 2018, 2022 Dimeo Ltd. under the terms of the GNU GPL, Version 3.0 (https://www.dimeo.ru/)
 * @license   https://gitlab.com/nx-2/admin/-/blob/master/LICENSE.md
 * @author    A. Shchepetov
 */


use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\User */

$this->title = 'Редактирование пользователя "' . $model->Login . '"';
$this->params['breadcrumbs'][] = ['label' => 'Пользователи(список)', 'url' => ['user/index']];
// $this->params['breadcrumbs'][] = ['label' => $model->FullName, 'url' => ['view', 'id' => $model->User_ID]];
$this->params['breadcrumbs'][] = 'редактирование';
?>
<div class="user-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/modules/admin/views/user/view.php
<?php
/**
 * @link      https://gitlab.com/nx-2/admin
 * @copyright Copyright © 2017, 2018, 2022 Dimeo Ltd. under the terms of the GNU GPL, Version 3.0 (https://www.dimeo.ru/)
 * @license   https://gitlab.com/nx-2/admin/-/blob/master/LICENSE.md
 * @author    A. Shchepetov
 */


use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\User */

$this->title = $model->User_ID;
$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['user/index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->User_ID], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->User_ID], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'User_ID',
            'Password',
            'Checked',
            'Language',
            'Created',
            'LastUpdated',
            'Email:email',
            'Login',
            'FullName',
            'LastName',
            'FirstName',
            'MidName',
            'Confirmed',
            'RegistrationCode',
            'Auth_Hash:ntext',
            'company',
            'job',
            'phone',
            'country',
            'city',
            'address:ntext',
            'street',
            'house',
            'building',
            'flat',
            'url:url',
            'company_profile',
            'sex',
            'birthday',
            'phone_prefix',
            'fax_prefix',
            'fax',
            'region',
            'district',
            'index_num',
            'open_email:email',
            'avatar',
            'UserType',
            'Text:ntext',
            'LastLoginDate',
            'publisher_id',
        ],
    ]) ?>

</div>