common/models/EmailNotice.php
<?php
/**
 * @link      https://gitlab.com/nx-2/admin
 * @copyright Copyright © 2017, 2018, 2022 Dimeo Ltd. under the terms of the GNU GPL, Version 3.0 (https://www.dimeo.ru/)
 * @license   https://gitlab.com/nx-2/admin/-/blob/master/LICENSE.md
 * @author    A. Shchepetov
 */
namespace common\models;

use Yii;

/**
 * This is the model class for table "email_notice".
 *
 * @property integer $id
 * @property string $name
 * @property string $email_subject
 * @property string $key_string
 *
 * @property EmailNoticeTemplate[] $emailNoticeTemplates
 * @property EmailNoticeTemplate | NULL $defaultTemplate
 */
class EmailNotice extends \common\models\CommonModel
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'email_notice';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'key_string'], 'required'],
            [['name', 'key_string'], 'string', 'max' => 50],
            [['email_subject'], 'string', 'max' => 100],
            [['key_string'], 'unique'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Название уведомления',
            'email_subject' => 'Тема письма',
            'key_string' => 'Имя события, генерируемого моделью',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDefaultTemplate()
    {
        return $this->hasOne(EmailNoticeTemplate::className(), ['notice_id' => 'id'])->where(['is_default' => 1]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEmailNoticeTemplates()
    {
        return $this->hasMany(EmailNoticeTemplate::className(), ['notice_id' => 'id']);
    }
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPublisherTemplate($publisherId = false)
    {
        if (!$publisherId) {
            return null;
        }
        return $this->hasOne(EmailNoticeTemplate::class, ['id' => 'template_id'])
            ->viaTable(
                'publisher_notice_template',
                ['notice_id' => 'id'],
                function ( $query )use ($publisherId) {
                    $query->where(['publisher_id' => $publisherId]);
                    return $query;
                }
        );

//        return $this->hasMany(EmailNoticeTemplate::className(), ['notice_id' => 'id']);
    }

    public function afterSave($insert, $changedAttributes) {
        parent::afterSave($insert, $changedAttributes);

        //манипуляции с папками и файлами там где хранятся шаблоны писем
        $viewPath = Yii::getAlias(Yii::$app->components['mailer']['viewPath']);
        if ( $insert ) {
            $dirName = $viewPath . '/' . $this->key_string;
//            if ( !dir($dirName) )
                mkdir($dirName, 0775, true); // создать по ключевому имени
        } else {
            // при изменении ключевого имени перенести всю старую папку (если она есть) во вновь созданную новую
            if ( array_key_exists('key_string', $changedAttributes) ) {
                if ( is_dir( $viewPath . '/' . $changedAttributes['key_string'] ) ) {
                    rename( $viewPath . '/' . $changedAttributes['key_string'] , $viewPath . '/' . $this->key_string );
                } else {
                    mkdir($viewPath . '/' . $this->key_string, 0775, true);
                }
            }
        }
    }
    public function afterDelete() {
        parent::beforeDelete();

        // манипуляции с файлами

        $viewPath = Yii::getAlias(Yii::$app->components['mailer']['viewPath']);
        if ( is_dir($viewPath . '/' . $this->key_string) ) {
            try {
                //удалить папку вместе со всем содержимым
                array_map( 'unlink', glob( $viewPath . '/' . $this->key_string . '/*' ) ); //delete all files in dir
                rmdir($viewPath . '/' . $this->key_string);
            } catch (Exception $ex) {

            }
        }
    }
}

backend/controllers/EmailNoticeController.php
<?php
/**
 * @link      https://gitlab.com/nx-2/front
 * @copyright Copyright © 2017, 2018, 2022 Dimeo Ltd. under the terms of the GNU GPL, Version 3.0 (https://www.dimeo.ru/)
 * @license   https://gitlab.com/nx-2/front/-/blob/master/LICENSE.md
 * @author    A. Shchepetov
 */
namespace backend\controllers;

use Yii;
use common\models\EmailNotice;
use backend\models\EmailNoticeSearch;
use backend\controllers\SiteController;
use yii\web\NotFoundHttpException;
use \common\services\EmailNoticeTestDataProvider;
use yii\filters\VerbFilter;
use backend\models\EmailLogSearch;
use common\models\EmaiLog;

/**
 * EmailNoticeController implements the CRUD actions for EmailNotice model.
 */
class EmailNoticeController extends SiteController
{
    public $dataProvider;
    
    public function __construct($id, $module, $config = array()) {
        parent::__construct($id, $module, $config);
        $this->dataProvider = new EmailNoticeTestDataProvider();
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => yii\helpers\ArrayHelper::merge(
                parent::behaviors()['access'],
                [
                    'rules' => [
                        [
                            'actions' => ['log', 'email-log','get-email-message','get-template-html', 'get-template'],
                            'allow' => true,
                            'roles' => ['subscribe_manager'],
                        ],
                        [
                            'actions' => ['index', 'resend-logged-email', 'update'],
                            'allow' => true,
                            'roles' => ['publisher'],
                        ],
                    ],
                ]
            ),
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
//                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all EmailNotice models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new EmailNoticeSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }
    public function actionLog()
    {
        $searchModel = new  EmailLogSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('log-index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }
    public function actionEmailLog($emailId = null)
    {
        Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        if (null == $emailId) {
            return ['status' => 'err', 'message' => 'email id is not supplied.'];
        }
        return [
            'status' => 'OK',
//            'html' => $email->body,
            'html' => $this->renderPartial('_email-message-modal', ['emailId' => $emailId]), // модальное окно bootstrap
        ];
    }
    public function actionGetEmailMessage($emailId = null)
    {
        if (null == $emailId) {
            return ['status' => 'err', 'message' => 'email id is not supplied.'];
        }
        $email = EmaiLog::findOne(['id' => intval($emailId)]);

        if (null == $email) {
            throw new NotFoundHttpException('The requested email message not found.');
        }
        return $this->renderPartial('_email-message-content', ['message' => $email]);
    }
    public function actionResendLoggedEmail($emailId = null, $recipient = 'currentUser')
    {
        Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;

        $recipient = ($recipient == 'currentUser' || $recipient == 'same') ? $recipient : 'currentUser';

        if (null == $emailId)
            return ['status' => 'err', 'message' => 'emailId was not supplied'];

        $loggedEmail = EmaiLog::findOne(['id' => intval($emailId)]);
        if (null == $loggedEmail)
            return ['status' => 'err', 'message' => 'requested message was not found'];
        $sent = $loggedEmail->resendImmediately($recipient);
        if ($sent) {
            return ['status' => 'OK'];
        } else {
            return ['status' => 'err', 'message' => 'При попытке отправить это письмо произошла ошибка. Письмо НЕ было отправлено.'];
        }
    }
    public function actionGetTemplateHtml( $templateId = false ){
        // возвращает результат рендеринга запрошенного шаблона (с тестовыми данными)
                
        Yii::$app->response->format = 'json';
        $toReturn = [];

        if ( !$templateId ) {
            $toReturn['status'] = 'err';
            $toReturn['errMessage'] = 'Отсутствует ИД шаблона';
            return $toReturn;
        }
        
        $data = ['templateId' => $templateId];
        
        $toReturn = [
            'status' => 'OK',
            'html' => $this->renderPartial('_email-template-content', $data), // модальное окно bootstrap 
        ];
        return $toReturn;
    }
    
    public function actionGetTemplate( $templateId=false ) 
    {
        if ( !$templateId ) {
            throw new \yii\web\NotFoundHttpException();
        }
        $this->layout = '@common/mail/layouts/html';
        $template = \common\models\EmailNoticeTemplate::findOne(['id' => $templateId]);

        if ( null == $template ) {
            throw new \yii\web\NotFoundHttpException();
        }

        try {
            $templateView = Yii::getAlias($template->template_file, true) . '.php';

        } catch (Exception $ex) {
            throw new \yii\web\NotFoundHttpException();
        }
        if ( !file_exists($templateView) ) {
            throw new \yii\web\NotFoundHttpException();
        }
        $noticeKeyString = $template->notice->key_string;
        $data = $this->dataProvider->getDataFor( $noticeKeyString );
        return $this->render($template->template_file, $data);
    }
    /**
     * Updates an existing EmailNotice model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $publisher = Yii::$app->user->identity->publisher;
        $relatedPublisherTemplate = \common\models\PublisherNoticeTemplate::findOne(['notice_id' => $model->id, 'publisher_id' => $publisher->id]);
        
        if ( Yii::$app->request->isPost ) {
            $data = Yii::$app->request->post('PublisherNoticeTemplate');
            if ($relatedPublisherTemplate == null) {
                $relatedPublisherTemplate = new \common\models\PublisherNoticeTemplate();
                $data['publisher_id'] = $publisher->id;
                $data['notice_id'] = $model->id;
            } 
            if ( $relatedPublisherTemplate->load($data, '') && $relatedPublisherTemplate->save() ) {
                Yii::$app->session->addFlash('success', 'Успешно сохранено.');
            } else {
                Yii::$app->session->addFlash('danger', 'Не сохранено!!.');
            }
        }
        return $this->render('update', [
            'model' => $model,
            'publisher' => $publisher,
            'relatedPublisherTemplate' => $relatedPublisherTemplate,
        ]);
    }
    /**
     * Finds the EmailNotice model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return EmailNotice the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = EmailNotice::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/views/email-notice/_email-message-content.php
<?php
/**
 * @link      https://gitlab.com/nx-2/admin
 * @copyright Copyright © 2017, 2018, 2022 Dimeo Ltd. under the terms of the GNU GPL, Version 3.0 (https://www.dimeo.ru/)
 * @license   https://gitlab.com/nx-2/admin/-/blob/master/LICENSE.md
 * @author    A. Shchepetov
 */
 if (isset($message)):?>
    <div style="background: white">
        <span>Адрес отправителя: </span><strong><?php echo($message->from); ?></strong><br>
        <span>Адрес получателя: </span><strong><?php echo($message->to); ?></strong><br>
        <span>Тема письма: </span><strong><?php echo($message->subject); ?></strong><br>
        <span>Дата: </span><strong><?php echo($message->time); ?></strong><br>
    </div>
    <h4 class="modal-title" id="email-message-label" style="padding-bottom: 15px;background: white">Содержание письма</h4>
    <div>
        <?php echo($message->body); ?>
    </div>
<?php endif; ?>

backend/views/email-notice/_emaillist.php
<?php
/**
 * @link      https://gitlab.com/nx-2/admin
 * @copyright Copyright © 2017, 2018, 2022 Dimeo Ltd. under the terms of the GNU GPL, Version 3.0 (https://www.dimeo.ru/)
 * @license   https://gitlab.com/nx-2/admin/-/blob/master/LICENSE.md
 * @author    A. Shchepetov
 */

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
use yii\helpers\Url;

?>

<div>
    <div id='email-message-modal-wrapper' >
        <div id='email-message-modal' class="modal fade" tabindex="-1" role="dialog" aria-labelledby="email-message-label">
            <div class="modal-dialog" role="document" style='width:auto;text-align:center;max-width:80%'>
                <div class="modal-content" style='display:inline-block;text-align:initial'>
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <h4 class="modal-title" id="email-message-label">Ваш шаблон</h4>
                        <div><input type='text' placeholder='ширина...' style='width: 70px;padding: 5px;border: 1px solid rgba(0,0,0,0.1);'></div>
                    </div>
                    <div class="modal-body"></div>
                    <div class="modal-footer">
                        <button type="button" class="btn bg-navy btn-flat" data-dismiss="modal">Закрыть</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <?php Pjax::begin(['id' => 'email-messages-list', 'enablePushState' => true]); ?>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
//                ['class' => 'yii\grid\SerialColumn'],
//                'id',
            [
                'class' => 'yii\grid\ActionColumn',
                'contentOptions' => ['style' => 'vertical-align: middle;'],
                // 'template' => '{update}',
                'template' => '{look}',
                // 'controller' => '',
                'buttons' => [
                    'look' => function ($url, $model, $key) {
                        $url = Url::to(['email-notice/email-log','id' => $key]);
                        return Html::a(
                            '',
                            $url,
                            [
                                'title' => 'Посмотреть письмо',
                                'aria-label' => 'Просмотр',
                                'data-pjax' => 0,
                                'class' => 'fa fa-envelope fa-font-18',
                                'data-id' => $key,
                                'onclick' => 'loadEmail(event)',
                            ]
                        );
                    },
                ],
            ],
            [
                'attribute' => 'success',
                'content' => function ($model, $key, $index, $column) {
                    return $model->success == 1 ? 'Отправлено' : 'НЕ отправлено';
                },
            ],
            'from',
            'to',
            'subject',
            [
                'attribute' => 'time',
                'content' => function ($model, $key, $index, $column) {
                    return date('d.m.y H:i', strtotime($model->time)) ;
                }
            ],
            'type',
            'publisher_id',
        ],
    ]); ?>
    <?php Pjax::end(); ?>
</div>
<script>
    function loadEmail(event) {
        if ( !event )
            event = window.event;

        var me = $(event.target);
        var id = me.data('id');
        $.ajax({
            'url' : '/email-notice/email-log/' + id,
            'dataType' : 'json',
            'type' : 'get',
        })
        .done( function ( response ) {
            if (response.status == 'OK') {
                var modalWrapper = $('#email-message-modal-wrapper');
                modalWrapper.html(response.html);
                var modal = $('#email-message-modal-wrapper #email-message-modal');
                if (modal.length > 0) {
                    modal.on('shown.bs.modal', function (event) {
                        setIframeSizes();
                    });
                    modal.modal('show');
                }
            } else {
                alert(response.message);
            }
        })
        .fail( function( a,b,c ) {
            console.log(a,b,c);
            alert('Что-то пошло не так. См.Консоль');

        } );
        event.preventDefault();
        return false;
    }
    function setIframeSizes( w, h ){
        w = !w ? 700 : w;
        h = !h ? false : h;

        var iframe = $('#popupMessageIframe');
        iframe.width(w + 'px');
        if ( h == false ) {
            var iframeBody = iframe.contents().find('body');
            h = iframeBody.height() + 20;
        }
        iframe.height(h + 'px');
    }
    function resendImmediately(id, recipient) {
        $.ajax({
            'url' : '/email-notice/resend-logged-email/' + id + '/' + recipient,
            'dataType' : 'json',
            'type' : 'get'
        }).done(function(response){
            if (response.status == 'OK')
                alert('Отправлено.');
            else
                alert(response.message);
        })
        .fail(function(a,b,c){
            console.log(a,b,c);
            alert('что-то пошло не так. См. консоль');
        });
    }


</script>

backend/views/email-notice/_form.php
<?php
/**
 * @link      https://gitlab.com/nx-2/admin
 * @copyright Copyright © 2017, 2018, 2022 Dimeo Ltd. under the terms of the GNU GPL, Version 3.0 (https://www.dimeo.ru/)
 * @license   https://gitlab.com/nx-2/admin/-/blob/master/LICENSE.md
 * @author    A. Shchepetov
 */


use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;


/* @var $this yii\web\View */
/* @var $model common\models\EmailNotice */
/* @var $form yii\widgets\ActiveForm */
?>
<div id='email-template-modal-wrapper'></div>
<div id='email-notice-form-wrapper' class='box box-primary email-notice-form'>
    <div class='box-header with-border'>
    </div>
    <div class='box-body'>
        <div class="row_">
            <div class='col-md-12 col-sm-12 col-xs-12' style='padding:0px 25px'>
                <div class="form-group">
                    <?php echo(Html::tag('label', $model->getAttributeLabel('name'), ['style' => 'display: block;', 'class' => 'control-label'])); ?>
                    <?php echo(Html::tag('span', $model->name, ['style' => 'display: block;border: 1px solid #d2d6de;padding: 6px 12px;'])); ?>
                </div>                
                <div class="form-group">
                    <?php echo(Html::tag('label', $model->getAttributeLabel('email_subject'), ['style' => 'display: block;', 'class' => 'control-label'])); ?>
                    <?php echo(Html::tag('span', $model->email_subject, ['style' => 'display: block;border: 1px solid #d2d6de;padding: 6px 12px;'])); ?>
                </div>                
            </div>
            <?php $form = ActiveForm::begin(); ?>
            <div class='col-md-12 col-sm-12 col-xs-12' style='padding:0px 25px'>
                <h3>Выберете подходящий шаблон:</h3>
                <input type="hidden" id="publishernoticetemplate-publisher_id" class="form-control" name="PublisherNoticeTemplate[publisher_id]" value="35">
                <input type="hidden" id="publishernoticetemplate-notice_id" class="form-control" name="PublisherNoticeTemplate[notice_id]" value="2">
                <input type="hidden" id="publishernoticetemplate-template_id" class="form-control" name="PublisherNoticeTemplate[template_id]" value="3">
                <?php 
                    if ($relatedPublisherTemplate !== null) {
                        echo(Html::tag('input','' , ['type' => 'hidden', 'id' => 'publishernoticetemplate-publisher_id', 'name' => 'PublisherNoticeTemplate[publisher_id]','value' => $relatedPublisherTemplate->publisher_id ]));
                        echo(Html::tag('input','' , ['type' => 'hidden', 'id' => 'publishernoticetemplate-notice_id', 'name' => 'PublisherNoticeTemplate[notice_id]','value' => $relatedPublisherTemplate->notice_id ]));
//                        echo(Html::tag('input','' , ['type' => 'hidden', 'id' => 'publishernoticetemplate-template_id', 'name' => 'PublisherNoticeTemplate[template_id]','value' => $relatedPublisherTemplate->template_id ]));
                        $templateId = $relatedPublisherTemplate->template_id;
                    } else {
                        echo(Html::tag('input','' , ['type' => 'hidden', 'id' => 'publishernoticetemplate-publisher_id', 'name' => 'PublisherNoticeTemplate[publisher_id]','value' => $publisher->id ]));
                        echo(Html::tag('input','' , ['type' => 'hidden', 'id' => 'publishernoticetemplate-notice_id', 'name' => 'PublisherNoticeTemplate[notice_id]','value' => $model->id ]));
//                        echo(Html::tag('input','' , ['type' => 'hidden', 'id' => 'publishernoticetemplate-template_id', 'name' => 'PublisherNoticeTemplate[template_id]','value' => '' ]));
                        $templateId = '';
                    }
                    if ( !empty($model->emailNoticeTemplates) ) {
                        foreach( $model->emailNoticeTemplates as $template ) {
                            $span = Html::tag('span', $template->name, ['style' => 'vertical-align: top;margin-right:10px']);
                            $radioLabel = Html::label('', 'template_' . $template->id, ['class'=> 'radio-check-label', 'style' => 'vertical-align: middle;margin:0px 10px 0px 0px;']);
                            $radioInput = Html::radio('PublisherNoticeTemplate[template_id]', $template->id == $templateId, ['id' => 'template_' . $template->id, 'value' => $template->id,]);
                            $showLink = Html::a('Посмотреть', '#showTemplate', ['onclick' => 'showTemplateContent(event)', 'data-id' => $template->id, 'style' => 'vertical-align: top;']);
                            $wrapDiv = Html::tag('div', $radioInput . $radioLabel . $span.  $showLink, ['class' => 'radio-check-wrap', 'style' => 'text-align: left;line-height: 30px;}']);
//                            echo(Html::label($template->name, 'template_' . $template->id , []));
//                            echo(Html::radio('PublisherNoticeTemplate[template_id]', $template->id == $templateId, ['id' => 'template_' . $template->id, 'value' => $template->id]));
//                            echo(Html::a('Посмотреть', '#showTemplate', ['onclick' => 'showTemplateContent(event)', 'data-id' => $template->id]));
//                            echo(Html::tag('div'));
                            echo($wrapDiv);
                        }
                    } else {
                        echo(Html::tag('h3', 'Извините... Но для этого типа Email оповещения пока что отсутствуют какие-либо шаблоны. Администраторы системы работают над этим:)..', []));
                    }
                ?>
            </div>
            <div class="col-md-12 col-sm-12 col-xs-12 form-group" style='padding: 0px 25px;margin-top: 20px;border-top: 1px solid rgba(0,0,0,0.1);padding-top: 20px;background: rgba(0,0,0,0.05);padding-bottom: 20px;'>
                <?= Html::submitButton('Сохранить', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
            </div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>
    <div class='box-footer'>
    </div>
    <script type="text/javascript">
    function showTemplateContent(event){
        if ( typeof event == 'undefined' ) {
            event = window.event;
        }
        
        event.preventDefault();
        $.ajax({
            url : '<?php echo( Url::to(['email-notice/get-template-html'], Yii::$app->request->getIsSecureConnection() ) ); ?>' + '/' + $(event.target).data('id'),
            type: 'get',
            dataType : 'json',
        }).done(function(response){
            if (response.status == 'OK') {
                $('#email-template-modal-wrapper').html(response.html);
                var modal = $('#email-template-modal-wrapper #email-notice-template-modal');
                if (modal.length > 0) {
                    modal.on('shown.bs.modal', function (event) {
                        setIframeSizes();
                    })
                    modal.modal('show');
                }
            } else {
                if ( response.hasOwnProperty('errMessage') ) {
                    alert( response.errMessage );
                }
            }
        })
        .fail(function(a,b,c){
            alert('что-то пошло не так. См. консоль');
            console,log(a);
            console,log(b);
            console,log(c);
        });
        return false;
    }
    function setIframeSizes( w, h ){
        w = !w ? 700 : w;
        h = !h ? false : h;
        
        var iframe = $('#popupTemplateIframe');
        iframe.width(w + 'px');
        if ( h == false ) {
            var iframeBody = iframe.contents().find('body');
            h = iframeBody.height() + 20;
        }
        iframe.height(h + 'px');
    }
</script>

backend/views/email-notice/_list.php
<?php
/**
 * @link      https://gitlab.com/nx-2/admin
 * @copyright Copyright © 2017, 2018, 2022 Dimeo Ltd. under the terms of the GNU GPL, Version 3.0 (https://www.dimeo.ru/)
 * @license   https://gitlab.com/nx-2/admin/-/blob/master/LICENSE.md
 * @author    A. Shchepetov
 */

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
use yii\helpers\Url;

?>

<div>
    <div id='email-template-modal-wrapper'></div>
    <?php Pjax::begin(['id' => 'email-notices-list', 'enablePushState' => true]); ?>    
        <?= GridView::widget([
            'dataProvider' => $dataProvider,
            'filterModel' => $searchModel,
            'columns' => [
//                ['class' => 'yii\grid\SerialColumn'],
//                'id',
                [
                    'class' => 'yii\grid\ActionColumn',
                    'contentOptions' => ['style' => 'vertical-align: middle;'],
                    // 'template' => '{update}',
                    'template' => '{update}',
                    // 'controller' => '',
                    'buttons' => [
                        'update' => function ($url, $model, $key) {
                            $url = Url::to(['email-notice/update','id' => $key]);
                            return Html::a(
                                '',
                                $url,
                                [
                                    'title' => 'редактировать',
                                    'aria-label' => 'редактировать',
                                    'data-pjax' => 0,
                                    'class' => 'fa fa-gear fa-font-18',

                                ]
                            );
                        },
                    ],
                ],
                'name',
                'email_subject',
                [
//                    'attribute' => 'PublisherTemplate',
                    'content' => function( $model, $key, $index, $column ) {
                            $template = $model->getPublisherTemplate( Yii::$app->user->identity->publisher->id )->one();
                            if ( $template === null ) {
                                $template = $model->defaultTemplate;
                            }
                            if ( $template !== null ) {
                                $showLink = Html::a('Просмотр', '#showTemplate', ['data-id' => $template->id,  'onclick' => 'showTemplateContent(event)']);
    //                            $showLink = Html::a($template->name, '#showTemplate', ['data-id' => $key,  'onclick' => 'showTemplateContent(event)']);
    //                            $contentSpan = Html::tag('span',$template->template_file , ['style' => 'margin-right: 7px']);
                                $contentSpan = Html::tag('span',$template->name, ['style' => 'margin-right: 7px']);
                                return $contentSpan . $showLink;
                            } else {
                                return(Html::tag('span', 'Шаблон отсутствует', ['style' => 'border-bottom: 1px dashed #bebebf;', 'class' => 'text-muted']));
                            }
                            
                    },
                ],
            ],
        ]); ?>
    <?php Pjax::end(); ?>
</div>
<script type="text/javascript">
    function showTemplateContent(event){
        if ( typeof event == 'undefined' ) {
            event = window.event;
        }
        
        event.preventDefault();
        $.ajax({
            url : '<?php echo( Url::to(['email-notice/get-template-html'], Yii::$app->request->getIsSecureConnection() ) ); ?>' + '/' + $(event.target).data('id'),
            type: 'get',
            dataType : 'json',
        }).done(function(response){
            if (response.status == 'OK') {
                $('#email-template-modal-wrapper').html(response.html);
                var modal = $('#email-template-modal-wrapper #email-notice-template-modal');
                if (modal.length > 0) {
                    modal.on('shown.bs.modal', function (event) {
                        setIframeSizes();
                    })
                    modal.modal('show');
                }
            } else {
                if ( response.hasOwnProperty('errMessage') ) {
                    alert( response.errMessage );
                }
            }
        })
        .fail(function(a,b,c){
            alert('что-то пошло не так. См. консоль');
            console,log(a);
            console,log(b);
            console,log(c);
        });
        return false;
    }
    function setIframeSizes( w, h ){
        w = !w ? 700 : w;
        h = !h ? false : h;
        
        var iframe = $('#popupTemplateIframe');
        iframe.width(w + 'px');
        if ( h == false ) {
            var iframeBody = iframe.contents().find('body');
            h = iframeBody.height() + 20;
        }
        iframe.height(h + 'px');
    }
</script>
    